### ISSUE TITLE
Add "mapping" category

### ISSUE THREAD

**Issue by cmutel** [brightway-lca/randonneur#10]
The current verbs are based around data *transformations*, but we also need to support [data *mappings*](https://github.com/fjuniorr/flowmapper/issues/1). These do not necessarily lead to a change in the underlying source or target data, but express a relationship between them.

The verb name can be *mapping* (or maybe something else?). It is up to clients to determine what they do with this information.

**Comment by fjuniorr** [comment]
> The current verbs are based around data _transformations_, but we also need to support [data _mappings_](https://github.com/fjuniorr/flowmapper/issues/1). These do not necessarily lead to a change in the underlying source or target data, but express a relationship between them.

This is nice! 

Have you though about how you will align this verb with the others in terms of return value when multiple verbs are present in the same data migration file? I say this because the current verbs are called because of their _side effect_ to transform the underlying data. However for mapping you need metadata about the match as a return value to be able to do something afterwards.

As an example while working on https://github.com/fjuniorr/flowmapper/pull/70 initially I was using `migrate_datasets` to transform the flows. However I needed some way to extract the `conversion_factor` from a change such as:

```json
  {
    "source": {
      "name": "Ammonia, as N"
    },
    "target": {
      "name": "Ammonia"
    },
    "conversion_factor": 1.2142857142857142
  }
```

for additional [processing](https://github.com/fjuniorr/flowmapper/pull/70/commits/5cd2df6b2a9261dcc00deb8e7b06c3115b3b2b1e#diff-7a0304d37ee23e71cbce6b871ee629d26e4c74904b70d458b97a4a0603526ebcR30).

Another different but related question is what would the `target` node would represent in this new verb (or even if it will be present at all).

> The verb name can be _mapping_ (or maybe something else?). 

How about `match`?

**Comment by cmutel** [comment]
@fjuniorr I am tempted to mark this as "won't fix", as I am worried about scope creep. Here is our current state:

- I came full circle on your idea to use JSONPath - I have updated `randonneur` to include a `mapping` section which shows where the attributes in the original files are located. See [the README](https://github.com/brightway-lca/randonneur/blob/main/README.md) for examples (and [randonneur_data](https://github.com/brightway-lca/randonneur_data)).
- `flowmapper` is *only* for biosphere flows, and there I do think there is a fundamental underlying ontology for all biosphere flows. See [my fork](https://github.com/cmutel/flowmapper) for details. But I should add XPath/similar to the fork to show how the values are imported - ideally this would work automatically, but not all data formats support structured expression languages.

**Comment by fjuniorr** [comment]
Sorry @cmutel I missed the original notification!

I don't have the full context currently loaded in my brain but I'm sure you are making the right call here.

**Comment by cmutel** [comment]
No worries, and thanks again! Your ideas were super helpful, even if I did resist some of them at first :)

In the end we allowed each file to define its own data schema, and user XPath or JSONPath as appropriate, depending on the input data source, see https://github.com/brightway-lca/randonneur_data/blob/main/randonneur_data/data/simapro-9-ecoinvent-3.8-biosphere-manual-matches.json#L23.
